name: Convert XML to Markdown
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Install realpath
        run: |
          sudo apt-get update
          sudo apt-get install -y realpath

      - name: Checkout DocusaurusWebsite repository
        uses: actions/checkout@v4
        with:
          repository: Pantagrueliste/CavrianaCorr_FrontEnd
          path: CavrianaCorr_FrontEnd
          token: ${{ secrets.DOCUSAURUS_REPO_SECRET }}

      - name: Download Saxon and XML Resolver
        run: |
          wget -O saxon.jar https://repo1.maven.org/maven2/net/sf/saxon/Saxon-HE/10.6/Saxon-HE-10.6.jar
          wget -O xml-resolver.jar https://repo1.maven.org/maven2/xml-resolver/xml-resolver/1.2/xml-resolver-1.2.jar

      - name: Create docs directory if it doesn't exist
        run: mkdir -p CavrianaCorr_FrontEnd/docs

      - name: Convert XML to Markdown by Year
        run: |
          set +e
          for file in ./letters/*.xml; do
            if [[ "$file" != "./letters/persNames.xml" && "$file" != "./letters/placeNames.xml" ]]; then
              if [ -f "$file" ]; then
                filename=$(basename "$file")
                filepath=$(realpath "$file")
                fileurl="file://$filepath"

                queryOutput=$(
                  java -cp saxon.jar:xml-resolver.jar net.sf.saxon.Query \
                    -qs:"declare namespace tei='http://www.tei-c.org/ns/1.0'; 
                         declare option saxon:output 'omit-xml-declaration=yes'; 
                         substring(doc('$fileurl')/tei:TEI/tei:teiHeader/tei:profileDesc/tei:correspDesc/tei:correspAction[@type='sent']/tei:date/@when,1,4)" \
                    -wrap=no 2>&1
                )
                rc=$?
                if [ $rc -ne 0 ]; then
                  echo "Saxon Query failed with exit code $rc for $file"
                  echo "Output: $queryOutput"
                  continue
                fi

                rawYear="$(echo "$queryOutput" | grep -Eo '^[0-9]{1,4}' || true)"
                if [ -z "$rawYear" ]; then
                  rawYear="unknownYear"
                fi

                mkdir -p "CavrianaCorr_FrontEnd/docs/$rawYear"
                output_file="CavrianaCorr_FrontEnd/docs/$rawYear/${filename%.*}.md"
                echo "Converting $file -> $output_file (year=$rawYear)"

                java -cp saxon.jar:xml-resolver.jar net.sf.saxon.Transform \
                  -s:"$file" \
                  -xsl:transform.xsl \
                  -o:"$output_file"
                transform_rc=$?
                if [ $transform_rc -ne 0 ]; then
                  echo "Saxon Transform failed with exit code $transform_rc for $file"
                fi
              fi
            fi
          done
          exit 0

      - name: Commit and push changes
        run: |
          cd CavrianaCorr_FrontEnd
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs/
          git diff --cached --quiet || git commit -m "Update converted Markdown files"
          git push origin main
