name: Convert XML to Markdown

on:
  push:
    branches:
      - main
    paths:
      - 'letters/*.xml'
      - 'transform.xsl'

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout TEI repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Checkout Docusaurus repo
        uses: actions/checkout@v4
        with:
          repository: Pantagrueliste/CavrianaCorr_FrontEnd
          path: CavrianaCorr_FrontEnd
          token: ${{ secrets.DOCUSAURUS_REPO_SECRET }}

      - name: Download Saxon
        run: |
          wget -O saxon.jar https://repo1.maven.org/maven2/net/sf/saxon/Saxon-HE/10.6/Saxon-HE-10.6.jar

      - name: Create docs folder
        run: mkdir -p CavrianaCorr_FrontEnd/docs

      - name: Convert XML to Markdown by Year
        run: |
          set -e
          for file in letters/*.xml; do
            if [[ "$file" != "letters/persNames.xml" && "$file" != "letters/placeNames.xml" ]]; then
              if [ -f "$file" ]; then
                echo "Processing $file"
                filename=$(basename "$file" .xml)
                filepath=$(realpath "$file")
                fileurl="file://$filepath"
                
                yearRaw=$(
                  java -cp saxon.jar net.sf.saxon.Query \
                    -qs:"declare namespace tei='http://www.tei-c.org/ns/1.0'; 
                         let \$date := doc('$fileurl')//tei:correspAction[@type='sent']/tei:date/@when
                         return normalize-space(substring(\$date, 1, 4))" \
                    | grep -o '[0-9]\{4\}' || echo "unknownYear"
                )
                
                year=${yearRaw:-unknownYear}
                yearDir="CavrianaCorr_FrontEnd/docs/$year"
                mkdir -p "$yearDir"
                output_file="$yearDir/${filename}.md"
                echo "Converting $file -> $output_file (year=$year)"
                java -cp saxon.jar net.sf.saxon.Transform \
                  -s:"$file" \
                  -xsl:"transform.xsl" \
                  -o:"$output_file"
              fi
            fi
          done

      - name: Pull before pushing
        run: |
          cd CavrianaCorr_FrontEnd
          git pull origin main

      - name: Commit and push
        run: |
          cd CavrianaCorr_FrontEnd
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs/
          # Only commit if there are changes
          git diff --cached --quiet || git commit -m "Update converted Markdown files"
          git push origin main
