name: Production Deployment with Final Validation

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download and Extract Jing
        run: |
          wget https://github.com/relaxng/jing-trang/releases/download/V20220510/jing-20220510.zip
          unzip jing-20220510.zip
          mkdir -p jing/bin
          cp jing-20220510/bin/jing.jar jing/bin/

      - name: Download TEI Schema (tei_all.rng)
        run: |
          mkdir -p schemas
          wget -O schemas/tei_all.rng https://tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng

      - name: Validate TEI Files in letters/
        run: |
          XML_FILES=$(find ./letters -type f -name "*.xml")
          if [ -n "$XML_FILES" ]; then
            echo "Validating TEI files in the letters folder..."
            find ./letters -type f -name "*.xml" -exec java -jar ./jing/bin/jing.jar schemas/tei_all.rng {} +
          else
            echo "No XML files found in the letters folder."
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Production
        run: |
          echo "Deploying to production..."
          # Insert your production deployment commands here
