name: TEI Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate TEI files
      uses: rojobuffalo/validate-tei@v1
      with:
        files: '*.xml'
