name: Validate TEI Documents

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Download and Extract Jing
        run: |
          wget https://github.com/relaxng/jing-trang/releases/download/V20220510/jing-20220510.zip
          unzip jing-20220510.zip -d jing
          echo "alias jing='java -jar $(pwd)/jing/bin/jing.jar'" >> $GITHUB_ENV

      - name: Download TEI Schema (tei_all.rng)
        run: |
          mkdir -p schemas
          wget -O schemas/tei_all.rng https://tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng

      - name: Validate TEI Files
        run: |
          find . -name "*.xml" -exec sh -c 'jing schemas/tei_all.rng "$@"' _ {} +
