name: Update Cavriana Heatmap

on:
  push:
    branches: [ main ]
    paths:
      - 'letters/*.xml'  # Trigger when new letters are added
      - 'letter_parser.py'
      - 'cavriana_heatmap.py'

jobs:
  update-heatmap:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout CavrianaCorr repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy lxml
        
    - name: Generate letter metadata
      run: |
        python letter_parser.py
        
    - name: Generate heatmap component
      run: |
        python cavriana_heatmap.py
        
    - name: Checkout Docusaurus frontend repository
      uses: actions/checkout@v3
      with:
        repository: Pantagrueliste/CavrianaCorr_FrontEnd
        path: frontend
        token: ${{ secrets.DOCUSAURUS_REPO_SECRET }}
        
    - name: Update heatmap component in frontend
      run: |
        # Create components directory if it doesn't exist
        mkdir -p frontend/src/components
        # Copy the generated heatmap component
        cp CavrianaHeatmap.jsx frontend/src/components/
        
    - name: Commit and push changes to frontend
      run: |
        cd frontend
        git config user.name "GitHub Actions Bot"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add src/components/CavrianaHeatmap.jsx
        # Only commit if there are changes
        git diff --cached --quiet || git commit -m "Update Cavriana letter heatmap visualization"
        git push
